# global_costmap:
#   global_costmap:
#     ros__parameters:
#       use_sim_time: True
#       global_frame: map
#       robot_base_frame: base_footprint
#       update_frequency: 1.0
#       publish_frequency: 1.0
#       width: 10
#       height: 10
#       resolution: 0.05
#       robot_radius: 0.22
#       rolling_window: false
#       track_unknown_space: true

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: True
      global_frame: map
      robot_base_frame: base_footprint
      update_frequency: 1.0
      publish_frequency: 1.0
      width: 15    # Changed from 10 to 15 meters
      height: 15   # Changed from 10 to 15 meters
      resolution: 0.05
      robot_radius: 0.22
      rolling_window: false
      track_unknown_space: true
      # ... rest of config stays the same
      
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        enabled: True
        subscribe_to_updates: True
        track_unknown_space: true
        use_maximum: false
        lethal_cost_threshold: 100
        trinary_costmap: true
      
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: True
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
      
      always_send_full_costmap: True